#!name=彩云天气SVIP
#!desc=彩云天气SVIP
# Script 2
# 彩云天气SVIP=type=http-response,requires-body=1,max-size=0,pattern=^https:\/\/biz\.caiyunapp\.com\/v2\/user\?app_name\=weather,script-path=https://raw.githubusercontent.com/Fedlimit/Script/main/colorweather.js

[Script]
彩云天气SVIP=type=http-response,requires-body=1,max-size=0,pattern=https?:\/\/biz\.caiyunapp\.com\/(membership_rights|v2\/user),script-path=https://raw.githubusercontent.com/Fedlimit/Script/main/caiyun.js

[MITM]
hostname= %APPEND% biz.caiyunapp.com
