#!name=APP启动页去广告
#!desc=APP启动页去广告

[URL Rewrite]
# > 12123
^https:\/\/gab\.122\.gov\.cn\/eapp\/m\/sysquery reject


# ======= A ======= #

# > acfun
^https?:\/\/api-new\.app\.acfun\.cn\/rest\/app\/flash\/screen\/ reject
# > alibaba
^https?:\/\/acs\.m\.taobao\.com\/gw\/mtop\.alibaba\.advertisementservice\.getadv\/ reject


# ======= C ======= #

# > cainiao
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.(show|mshow)\.cn\/ reject
# > csdn
^https?:\/\/app-gw\.csdn\.net\/silkroad-api\/api\/v\d\/assemble\/list\/pub\/channel\/app_open_screen_ad reject


# ======= D ======= #

# > dongkakongjian
^https?:\/\/m\.creditcard\.ecitic\.com\/citiccard\/mbk\/appspace-getway\/getWay\/dkkj-system-web\/system\/v\d\/init-config reject


# ======= E ======= #

# > elema
^https?:\/\/elemecdn.com\/.+\/sitemap reject
^https?:\/\/fuss10.elemecdn.com\/.+\/w\/640\/h\/\d{3,4} reject
^https?:\/\/fuss10.elemecdn.com\/.+\/w\/750\/h\/\d{3,4} reject
^https?:\/\/fuss10.elemecdn.com\/.+.mp4 reject
^https?:\/\/www1.elecfans.com\/www\/delivery\/ reject


# ======= F ======= #

# > feizhu
^https:\/\/acs\.m\.taobao\.com\/gw\/mtop\.fliggy\.crm\.screen\.allresource reject


# ======= H ======= #

# > huangyouxiangji
^https?:\/\/api4\.bybutter\.com\/v\d\/app\/placements\/\d\/advertisements reject
# > hanglvzongheng
^https?:\/\/(discardrp|startup)\.umetrip\.com\/gateway\/api\/umetrip\/native reject


# ======= J ======= #

# > jingdong
^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(start|queryMaterialAdverts) reject
^https?:\/\/(bdsp-x|dsp-x)\.jd\.com\/adx\/ reject
# > jingdongjinrong
^https?:\/\/ms\.jr\.jd\.com\/gw\/generic\/aladdin\/(new)?na\/m\/getLoadingPicture reject
# > jiaohangmaidanba
^https?:\/\/creditcardapp\.bankcomm\.com\/mapp\/common\/(queryGuidePageAds|getPopAds)\.do$ reject
# > jianhanglife
^https?:\/\/yunbusiness\.ccb\.com\/clp_service\/txCtrl\?txcode=A3341A00(2|9) reject


# ======= M ======= #

# > MeiTuan
^https?:\/\/peisongapi\.meituan\.com\/client\/getInitiateImage reject
^https?:\/\/img\.meituan\.net\/(adunion|display|midas)\/\w+\.(gif|jpg|jpg\.webp)$ reject
^https?:\/\/(s3plus|flowplus)\.meituan\.net\/v\d\/\w+\/linglong\/\w+\.(gif|jpg|mp4) reject
^https?:\/\/p\d\.meituan\.net\/(bizad|wmbanner)\/\w+\.jpg reject
^https?:\/\/p\d\.meituan\.net\/movie\/\w+\.jpg\?may_covertWebp reject
# > MeiTuanWaiMai
^https?:\/\/img\.meituan\.net\/(bizad|brandCpt)\/\w+\.(png|jpg) reject
^https?:\/\/wmapi\.meituan\.com\/api\/v\d+\/loadInfo\? reject
^https?:\/\/wmapi\.meituan\.com\/api\/v\d\/startpicture reject
^https?:\/\/www\.meituan\.com\/api\/v\d\/appstatus\?ad reject
# > maidanba
^https?:\/\/creditcardapp\.bankcomm\.cn\/mappweb_interface\/common\/(qryPopAds|qryLaunchAds)\.do reject


# ======= N ======= #

# > nanfanghangkong
^https?:\/\/3g\.csair\.com\/CSMBP\/bookProcess\/homepopup\/queryAdvertisement reject


# ======= P ======= #

# > pikpak
https://access.mypikpak.com/access_controller/v1/area_accessible reject
# > pinduoduo
^https?:\/\/api\.(pinduoduo|yangkeduo)\.com\/api\/cappuccino\/splash reject
# > pufayinhang
^https?:\/\/lban\.spdb\.com\.cn\/mspmk-web-component\/(getAdvList|prefetchAdvList)\.ah reject


# ======= S ======= #

# > shaoshupai
https://ios.sspai.com/api/v3/recommend/page/get\?ad.*ios_home_modal reject
# > ShunFeng
^https?:\/\/ccsp-egmas\.sf-express\.com\/cx-app-base\/base\/app\/appVersion\/detectionUpgrade reject
https://ccsp-egmas.sf-express.com/cx-app-base/base/app/ad/queryAdImages reject
^https?:\/\/shopic\.sf-express\.com\/crm\/mobile\/common\/flashscreen reject


# ======= X ======= #

# > XianYu
^https:\/\/gw.alicdn.com\/mt\/ reject
^https:\/\/gw.alicdn.com\/tfs\/.+\d{3,4}-\d{4} reject
^https:\/\/gw.alicdn.com\/tps\/.+\d{3,4}-\d{4} reject
# > xiaolishenghuo
^https?:\/\/mpos-pic\.helipay\.com\/upload\/images\/advertisment reject


# ======= Z ======= #

# > zhangshangshenghuo
^https?:\/\/mlife\.cmbchina\.com\/ClientFaceService\/api\/mlife\.clientface\.clientservice\.api\.advertiseService\/preCacheAdvertiseSec reject
# > zhongguoyidong
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/DN\/init\/startInit reject
^https?:\/\/client\.app\.coc\.10086\.cn\/biz-orange\/DN\/explorePage\/getAdverList reject
# > zhongguoyidongguangdong
^https?:\/\/gd\.10086\.cn\/gmccapp\/serv\/\?servicename=GMCCAPP_704_002_001_001 reject
# > zhaoshangyinhang
^https?:\/\/webappcfg\.paas\.cmbchina\.com\/v1\/func\/getmarketconfig reject
# > zuoyebang
^https?:\/\/syh\.zybang\.com\/com\/adx\/ reject
# > zhongguoyinhang
^https?:\/\/mbs\.boc\.cn\/ubas-mgateway-static\/images\/advertType\/.+.jpg reject-img


[MITM]
hostname = %APPEND% app-gw.csdn.net, cn-acs.m.cainiao.com, acs.m.taobao.com, creditcardapp.bankcomm.cn, webappcfg.paas.cmbchina.com, m.creditcard.ecitic.com, lban.spdb.com.cn, access.mypikpak.com, 3g.csair.com, api-new.app.acfun.cn, gd.10086.cn, sdk.alibaba.com.ailbaba.me, yunbusiness.ccb.com, client.app.coc.10086.cn, ios.sspai.com, g.alicdn.com, api.pinduoduo.com, api.yangkeduo.com, mpos-pic.helipay.com, peisongapi.meituan.com, syh.zybang.com, api. img.meituan.net, discardrp.umetrip.com, startup.umetrip.com, acs.m.taobao.com, www.meituan.com, ccsp-egmas.sf-express.com, gab.122.gov.cn, creditcardapp.bankcomm.com, elemecdn.com, fuss10.elemecdn.com, www1.elecfans.com, s3plus.meituan.net, flowplus.meituan.net, p*.meituan.net, ms.jr.jd.com, wmapi.meituan.com, bdsp-x.jd.com, dsp-x.jd.com, api.m.jd.com
